# Generated by Django 6.0.3 on 2026-04-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cuisine',
            field=models.CharField(choices=[('italian', 'Italian'), ('japanese', 'Japanese'), ('american', 'American'), ('mexican', 'Mexican'), ('asian', 'Asian'), ('steakhouse', 'Steakhouse'), ('korean', 'Korean'), ('kazakh', 'Kazakh')], default='italian', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('burgers', 'Burgers'), ('pasta', 'Pasta'), ('salads', 'Salads'), ('sides', 'Sides'), ('drinks', 'Drinks'), ('desserts', 'Desserts'), ('sushi', 'Sushi'), ('ramen', 'Ramen'), ('tacos', 'Tacos'), ('steak', 'Steak')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('burgers', 'Burgers'), ('pasta', 'Pasta'), ('salads', 'Salads'), ('sides', 'Sides'), ('drinks', 'Drinks'), ('desserts', 'Desserts'), ('sushi', 'Sushi'), ('ramen', 'Ramen'), ('tacos', 'Tacos'), ('steak', 'Steak')], max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('italian', 'Italian'), ('japanese', 'Japanese'), ('american', 'American'), ('mexican', 'Mexican'), ('asian', 'Asian'), ('steakhouse', 'Steakhouse'), ('korean', 'Korean'), ('kazakh', 'Kazakh')], max_length=50),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
